### ISSUE TITLE
How can on recieve data?

### ISSUE THREAD

**Issue by dsomel21** [vigetlabs/ruby_spark#6]
For example, 

`device.function("doThing", command)`

The doThing function is supposed to return an integer, but there's no way in our Rails app to retrieve it.

**Comment by efatsi** [comment]
When you call `device.function("doThing", "command"), that should return the integer value that is returned from the Particle device. Are you seeing something else?

Code: https://github.com/vigetlabs/ruby_spark/blob/e4fa7046cb17b20d1f4e5a2681da68fc1a8a88a2/lib/ruby_spark/device.rb#L27-L32
Test: https://github.com/vigetlabs/ruby_spark/blob/e4fa7046cb17b20d1f4e5a2681da68fc1a8a88a2/spec/spark/device_spec.rb#L29-L36

**Comment by dsomel21** [comment]
Thank you @efatsi  for replying so timely. 

The function is running properly. When the a string `command` is passed, the firmware is able to parse it and send the response to the Linux Command Line / Shell, I believe. So, it's the value that's being sent to the Linux Shell that I am unable to reach. 

Typing this out made me realize that this isn't an issue between device and the Particle, but about the device and the Linux Shell. What do you thing?

**Comment by efatsi** [comment]
Sorry @dsomel21 but I'm not really following what your problem is, and how/why the linux shell plays into everything. If you want to try to explain again what your process is and what pieces are involved, i'm happy to help you think through things. Otherwise, good luck!
